# Generated by Django 4.0.1 on 2022-04-05 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_bond_publishedby_alter_bond_purchasedby_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bond',
            name='isPurchased',
            field=models.CharField(choices=[('PURCHASED', 'PURCHASED'), ('AVAILABLE', 'AVAILABLE')], default='AVAILABLE', max_length=50),
        ),
    ]
