# Generated by Django 4.0.1 on 2022-04-06 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_bond_ispurchased'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bond',
            name='isPurchased',
            field=models.CharField(choices=[('purchased', 'PURCHASED'), ('available', 'AVAILABLE')], default='available', max_length=50),
        ),
    ]
